### ISSUE TITLE
Create .gitignore files

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/restaurant-manager#8]
Set up a .gitignore file with the following things in mind: React, .NET C#, Firebase. 

For easy generation use: [gitignore.io](https://www.gitignore.io/)

**Comment by nidhineshnand** [comment]
Can we have a nested .gitignore structure where the React project folder has a separate gitignore file that is specific to the React project and the same with the .NET folder? It would make it clearer to read and make changes

**Comment by wshin387** [comment]
or have 2 repos? for frontend and backend
